### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by SandLYJ** [paganpasta/coss-pytorch#1]
In your paper, "To define space similarity, we first construct the transpose matrix of features and its normalized version . The space similarity loss is" 
![屏幕截图 2024-10-11 212213](https://github.com/user-attachments/assets/8cfa12f5-f9f9-43c0-9c04-ab978a1dcc33)

Why transposing the features is space similarity? Can you tell me the meaning in it? I can not understand this opearation.

Thanks.

**Comment by paganpasta** [comment]
Hi @LYJhere 

This is for simplicity and using the cosine subroutine. Otherwise, one would have to implement two different cosine similarity functions to work along the column and work along the row. We are interested in computing two different similarity scores one for the batch dimension (space dimension) and one for the feature dimension. See code [here](https://github.com/paganpasta/coss-pytorch/blob/c0a753ffda7e711858e820a75024711c68bc7868/losses.py#L68) for more info.

Hope this helps.

**Comment by SandLYJ** [comment]
Ok, thanks for your reply.
Your idea("space similarity") is seemly similar with this paper
"Dimensional Contrastive Learning for Improving Self-Supervised Learning".

Aditya Singh ***@***.***> 于2024年10月12日周六 00:40写道：

**Comment by paganpasta** [comment]
Hi, thanks for the reference. 

I took a quick look, and yes the ideas are very similar with different motivations. 

Edit: Closing the issue for now. Feel free to re-open it for more queries.

**Comment by alokendumazumder** [comment]
Hi,

I am unable to undersdtand the structure of your saved models. You have provided links, in which it has data.pkl and a data folder with few "no format" files. Also, can you provide a quick and detailed overview on how to replicate the Tab 1?
